# version: '3'

services:
  # payload:
  #   image: node:18-alpine
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - .:/home/node/app
  #     - node_modules:/home/node/app/node_modules
  #   working_dir: /home/node/app/
  #   command: sh -c "yarn install && yarn dev"
  #   depends_on:
  #     - mongo
  #   env_file:
  #     - .env

  # mongo:
  #   image: mongo:latest
  #   ports:
  #     - '27017:27017'
  #   command:
  #     - --storageEngine=wiredTiger
  #   volumes:
  #     - data:/data/db
  #   logging:
  #     driver: none

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: payload
      POSTGRES_DB: payload
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/data/db

volumes:
  pgdata:
  # data:
  # node_modules:
